##
## Release static library
##
name: release
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: fogfish/cmake_build_action@master
        with:
          submodule_update: OFF
          run_tests: OFF
          cmake_args: -DCMAKE_BUILD_TYPE=Release ./libw2v
          create_package: OFF

      - uses: softprops/action-gh-release@v2.2.0
        with:
          name: v0.0.0
          tag_name: v0.0.0
          files: |
            libw2v/lib/libw2v.a
