##
## Release static library
##
name: release
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: fogfish/cmake_build_action@master
        with:
          submodule_update: OFF
          run_tests: OFF
          cmake_args: -DCMAKE_BUILD_TYPE=Release ./libw2v
          create_package: OFF

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libw2v/lib/libw2v.a
          asset_name: libw2v.a
          tag: v0.0.0
          overwrite: true
          body: "This is my release text"

