##
## Release static library
##
name: release
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: fogfish/cmake_build_action@master
        with:
          submodule_update: OFF
          run_tests: OFF
          cmake_args: -DCMAKE_BUILD_TYPE=Release ./libw2v
          create_package: OFF

      - uses: actions/upload-artifact@v2
        with:
          path: libw2v/lib/libw2v.a
          name: libw2v.a