##
## Release static library
##
name: release
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]

    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: fogfish/cmake_build_action@master
        with:
          config: ${{ matrix.configs }}
          submodule_update: OFF
          run_tests: OFF
          cmake_args: -DCMAKE_BUILD_TYPE=Release ./libw2v
          create_package: ON

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.tar.gz
          # asset_name: libw2v.${{ matrix.os }}.a
          tag: v0.0.0
          overwrite: true

